# Generated by Django 5.1.7 on 2025-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0009_vehiclereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='delivery_time_0_10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='delivery_time_10_20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
