# Generated by Django 5.1.7 on 2025-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrivehicles', '0010_vehicle_delivery_time_0_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
